// Smattering of http requets for testing the api.

#@base = http://localhost:3000
@base = https://rec-room.io


### Misc requests showing routing
###
GET {{base}}

###
GET {{base}}/stats

###
GET {{base}}/hello

###
GET {{base}}/bye

###
GET {{base}}/hello/bye

###
GET {{base}}/hello/bye/314512

### Contact CRUD ====================
###
GET {{base}}/contacts/111

###
DELETE {{base}}/contacts/111

###
GET {{base}}/contacts/111

###
POST {{base}}/contacts

{"id": "111",
"FirstName":"Bob",
"FamillyName": "Smith",
"DOB": "Nov 11, 1963",
"EMail": "foo@bar.com"
}

###
GET {{base}}/contacts/111

###
put {{base}}/contacts/111

{"id": "111",
"FirstName":"Johnny",
"FamillyName": "Smith",
"DOB": "Nov 11, 1963",
"EMail": "foo@bar.com"
}

###
GET {{base}}/contacts/1~

###
GET {{base}}/contacts
