// Smattering of http requets for testing the api.

#@base = http://localhost:3000
@base = https://rec-room.io

###
GET {{base}}

###
GET {{base}}/stats

###
GET {{base}}/hello

###
GET {{base}}/bye

###
GET {{base}}/hello/bye

###
GET {{base}}/hello/bye/314512

###
POST {{base}}/contacts

{"id": "Bill",
"FirstName":"Bill",
"FamillyName": "Smith",
"DOB": "Nov 11, 1963",
"EMail": "foo@bar.com"
}

###
GET {{base}}/contacts

###
GET {{base}}/contacts/12

###
put {{base}}/contacts/12

{"id": "12",
"FirstName":"Johnny",
"FamillyName": "Smith",
"DOB": "Nov 11, 1963",
"EMail": "foo@bar.com"
}

###
GET {{base}}/contacts/12

###
DELETE  {{base}}/contacts/12

###
GET {{base}}/contacts/12






